package de.adorsys.ledgers.sca.exception;

public enum SCAErrorCode {
    USER_SCA_DATA_NOT_FOUND,
    AUTH_CODE_GENERATION_FAILURE,
    SCA_METHOD_NOT_SUPPORTED,
    SCA_OPERATION_EXPIRED,
    SCA_OPERATION_NOT_FOUND,
    SCA_OPERATION_USED_OR_STOLEN,
    SCA_OPERATION_VALIDATION_FAILED
}
