package de.adorsys.ledgers.um.api.exception;

public enum UserManagementErrorCode {
    USER_NOT_FOUND,
    CONSENT_NOT_FOUND,
    INSUFFICIENT_PERMISSION,
    USER_ALREADY_EXISTS,
    TOKEN_CREATION_ERROR,
    RESET_PASSWORD_CODE_SENDING_ERROR,
    RESET_PASSWORD_CODE_INVALID,
    RESET_PASSWORD_CODE_EXPIRED
}
